### PR TITLE
fix for #5 and #6

### PR DESCRIPTION
**Pull request by TobiTenno**
fix for #5 and #6

### CODE REVIEW

**Comment by TobiTenno** [comment]
@kristenmills please review

**Comment by JSzaszvari** [comment]
This really needs to be merged. It's pretty non-functional without this.

**Comment by JSzaszvari** [comment]
@kristenmills Thanks! You rock 👍

**Comment by TobiTenno** [comment]
yay, glad you got it

**Comment by kristenmills** [comment]
Sorry I left this sitting for so long.

**Pull request merged**
